[project]
name = "Lazipaper"
version = "0.0.1"
description = "📄 Lazipaper: Automated Research Paper Tracker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.2.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
]
